figure('units','normalized','outerposition',[0 0 1 1]);
subplot(3,2,1);
load('travel.mat');
load('travel_rate.mat');
load('pitch.mat');
load('pitch_rate.mat');
plot(travel(1,:), travel(2,:));
title('travel');
subplot(3,2,2);
plot(travel_rate(1,:), travel_rate(2,:));
title('travel rate');
subplot(3,2,3);
plot(pitch(1,:), pitch(2,:));
title('pitch');
subplot(3,2,4);
plot(pitch_rate(1,:), pitch_rate(2,:));
title('pitch rate');
subplot(3,2,[5 6]);
plot(u(:,1), u(:,2));
title('u');
xlabel(strcat('time, q=', num2str(q)));
print(strcat('figures/10.2.3.q_', num2str(q)), '-depsc');
