figure('units','normalized','outerposition',[0 0 1 1]);
subplot(3,2,1);
load('travel.mat');
load('travel_rate.mat');
load('pitch.mat');
load('pitch_rate.mat');
plot(travel(1,:), travel(2,:));
title('travel');
subplot(3,2,2);
plot(travel_rate(1,:), travel_rate(2,:));
title('travel rate');
subplot(3,2,3);
plot(pitch(1,:), pitch(2,:));
title('pitch');
subplot(3,2,4);
plot(pitch_rate(1,:), pitch_rate(2,:));
title('pitch rate');
subplot(3,2,[5 6]);
plot(u(:,1), u(:,2));
title('u');
xlabel(strcat('time, q1=', num2str(q1), 'q2=', num2str(q2)));
print(strcat('figures/10.4.3.q1_', num2str(q1), '_q2_', num2str(q2), '_N_', num2str(N)), '-depsc');


figure('units','normalized','outerposition',[0 0 1 1]);
load('elevation.mat');
load('elevation_rate.mat');
subplot(2,1,1);
plot(elevation(1,:), elevation(2,:));
title('elevation');
subplot(2,1,2);
plot(elevation_rate(1,:), elevation_rate(2,:));
title('elevation rate');
xlabel(strcat('time, q1=', num2str(q1), 'q2=', num2str(q2)));
print(strcat('figures/10.4.3.elevation.q1_', num2str(q1), '_q2_', num2str(q2), '_N_', num2str(N)), '-depsc');